import Footer from './components/Footer/Footer';
import Navbar from './components/Navbar/Navbar';
import './globals.css';

export const metadata = {
  title: 'Netlix Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {/* main content */}
        {children}
        {/* closing main content */}
        <Footer />
      </body>
    </html>
  );
}
